#! /bin/sh

. ./common_macos.sh

flags="\
-DLIBTYPE=STATIC \
-DALSOFT_BACKEND_COREAUDIO=OFF \
-DALSOFT_BACKEND_WAVE=OFF \
-DALSOFT_UTILS=OFF \
-DALSOFT_EXAMPLES=OFF \
-DALSOFT_NO_CONFIG_UTIL=ON \
-DALSOFT_INSTALL_AMBDEC_PRESETS=OFF"

standard_cmake openal openal-soft-1.23.1 libopenal.a "$flags"
